<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hotel_booking"
 *
 * Auto generated by Extension Builder 2015-10-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Hotel Booking',
	'description' => 'Booking for hotel rooms, houses, cotttages etc ...',
	'category' => 'plugin',
	'author' => 'Renan Gautier, Julian Layen',
	'author_email' => 'rg.gloumi@gmail.com, layenjulian@gmail.com',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-7.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);